config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root :to => 'static_pages#home'

  get 'static_pages/about'
  get 'reports' => 'expenses#reports'

  resources :expenses
  
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :user
	has_many :expenses
	default_scope { order("created_at DESC") }
	validates :name , uniqueness: true
	validates :name , presence: true
end

app/models/expense.rb
class Expense < ActiveRecord::Base
	belongs_to :category
	belongs_to :user

	validates :amount, :category, :date, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :categories
  has_many :expenses, through: :categories

  after_create :create_default_categories

  DEFAULT_CATEGORIES = [
     {name: 'Phone bill'},
     {name: 'Entertainment'},
     {name: 'Rent'},
     {name: 'Travel'},
     {name: 'Parties'},
     {name: 'Gifts'},
     {name: 'Phone bill'},
     {name: 'Miscellaneous'}
  ]

  def create_default_categories
    DEFAULT_CATEGORIES.each do |default_attrs|
      self.categories.build(default_attrs)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :set_category, only: [:show, :edit, :update, :destroy]
	before_action :all_categories, only: [:create, :index]
	before_action :authenticate_user!
	respond_to :html, :js
	def new
		@category = Category.new
	end

	def create
		@user = current_user
		@category = @user.categories.create(category_params)
		if @category.save
			redirect_to categories_path
			flash[:success] = "New category created"
		else
			redirect_to new
		end
	end

	def edit
	end

	def update
		if @category.update_attributes(category_params)
			redirect_to categories_path
			flash[:success] = "Category updated successfully"
		else
			render 'edit'
		end
	end

	def destroy
		if @category.destroy
		redirect_to categories_path
		end
	end

	def index
		respond_to do |format|
			format.html
			format.js
		end
	end

	def show
	end

	private

	def set_category
		@category = Category.find(params[:id])
	end

	def category_params
		params.require(:category).permit(:name, :user_id)
	end

	def all_categories
		@categories = current_user.categories
		@categories =  Kaminari.paginate_array(@categories).page(params[:page]).per(5)
	end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	include ExpensesHelper
	before_action :authenticate_user!
	

	def new
		@expense = Expense.new
	end

	def create
		@expense = Expense.new(expense_params)
		if @expense.save
			redirect_to expenses_path
			flash[:success] = "New expence has been created"
		else
			redirect_to new_expense_path
		end
	end

	def edit
		@expense = Expense.find(params[:id])
	end

	def update
		@expense = Expense.find(params[:id])
		if @expense.update_attributes(expense_params)
			redirect_to expenses_path
			flash[:success] = "Expense has been updated"
		else
			render 'edit'
		end
	end

	def index
		sort = params[:type]
		
    	if sort == 'date'
    		@expenses = current_user.expenses.where("date >= ?", Time.zone.now.beginning_of_day)
    	elsif sort == 'week'
    		@expenses = current_user.expenses.where("date >= ?", Time.zone.now.beginning_of_week)  		
    	elsif sort == 'month'
    		@expenses = current_user.expenses.where("date >= ?", Time.zone.now.beginning_of_month)
    	elsif sort == 'year'
    		@expenses = current_user.expenses.where("date >= ?", Time.zone.now.beginning_of_year)
    	else
    		@expenses = current_user.expenses
    	end
    	@search = @expenses.search(params[:q])
  		@expenses = @search.result	
    	@expenses =  Kaminari.paginate_array(@expenses).page(params[:page]).per(5)
		respond_to do |format|
	      format.html
	      format.xls
	  end
    end

	def destroy
		@expense = Expense.find(params[:id])
		if @expense.destroy
			flash[:success] = "expense deleted"
			redirect_to expenses_path
		else
			redirect_to expenses_path
		end
	end

	def reports

		 from_date, to_date = current_week
	     @current_week_expenses = Expense.where('date BETWEEN ? AND ?', from_date, to_date)

	      from_date, to_date = current_month
	      @current_month_expenses = Expense.where('date BETWEEN ? AND ?', from_date, to_date)

	      from_date, to_date = current_month
	      @current_year_expenses = Expense.where('date BETWEEN ? AND ?', from_date, to_date)

        if params[:date_from].present? && params[:date_to].present?
	        date_from = Date.parse(params[:date_from])
	        date_to   = Date.parse(params[:date_to])
	        @range_expenses  = Expense.where('date BETWEEN ? AND ?', date_from.beginning_of_day, date_to.end_of_day)
        end      	      
    end


    def expense_sort
    	sort = params[:type]
    	if sort == 'date'
    		@expenses = current_user.expenses.where(:created_at => Date.today)
    	elsif sort == 'month'
    	elsif sort == 'year'
    	end
    	Rails.logger.debug "\nGETTING PARAMATERS----#{sort}\n"
    end



	private

	def expense_params
		params.require(:expense).permit(:amount, :date, :category_id, :description)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper

	def current_day
	  date = Date.today
	end

	def current_week
		date = Date.today
		[date.beginning_of_week, date.end_of_week]
	end

	def current_month
	  date = Date.today
	  [date.beginning_of_month, date.end_of_month]
	end

	def current_year
		date = Date.today
	    [date.beginning_of_year, date]
	end

	def sort_by_month(expenses)
		date = Date.today
		expenses.where(:created_at => date..date.end_of_month)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: { multipart: true , class: "form-horizontal", id: "category_form", remote: true}) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" class = "alert alert-warning">
      <h3 class = "alert alert-warning"><%= pluralize(@category.errors.count, "error") %> present in the form: </h3>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr>
  <div class="form-group">
    <%= f.label :name, "Name:" %><br>
    <div class="col-md-7">
    <%= f.text_field :name, class: "form-control"  %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :Submit, class: 'btn btn-success', data: { disable_with: "Please wait..." } %>
  </div>
<% end %>

app/views/categories/create.js.erb
$('#categories').html("<%= j (render @tasks) %>");
$('#category_form').slideUp(350);

app/views/categories/edit.html.erb
<h1>edit category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<div class="well">
<%= link_to "+ New Category", new_category_path, class: "btn btn-success",remote: true %>
</div>
<div id="category_form" style="display:none;"></div>
<%= paginate @categories %>
</br>
<%= page_entries_info @categories %>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if current_user.categories.count == 0 %>
      <tr>
        <td colspan="2">
          No categories found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @categories.each do |category| %>
        <tr>
          <td><%= link_to category.name, category %></td>
          <td><%= link_to "Edit", edit_category_path(category), class: "btn btn-primary" %>
              <%= link_to "Delete", category, method: :delete,
                    data: { confirm: "You sure?" }, class: 'btn btn-small btn-danger','data-turbolinks-eval' => false %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1> New Category </h1>
<%= render 'form' %>

app/views/categories/new.js.erb
$('#category_form').html("<%= j (render 'form') %>");
$('#category_form').slideDown(350);

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<table class="table table-bordered table-striped">
	<caption><%= @category.name %> expense details</caption>
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @category.expenses.count == 0 %>
      <tr>
        <td colspan="4">
          No expenses found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @category.expenses.each do |expense| %>
        <tr>
          <td><%= expense.date %></td>
          <td><%=expense.description%></td>
          <td><%= expense.amount %></td>
          <td><%= link_to "Edit", edit_expense_path(expense), class: "btn btn-primary" %>
              <%= link_to "Delete", expense, method: :delete,
                    data: { confirm: "You sure?" }, class: 'btn btn-small btn-danger' %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/expenses/_expense_search.html.erb
  <%= search_form_for @search do |f| %>
    	<%= f.text_field :description_cont, placeholder: "Expense Description" %>
   <%= f.submit "Search"%>
   <% end %>

app/views/expenses/_form.html.erb
<%= form_for(@expense, html: { multipart: true , class: "form-horizontal", id: "expense_form"}) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation" class = "alert alert-warning">
      <h3 class = "alert alert-warning"><%= pluralize(@expense.errors.count, "error") %> present in the form: </h3>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr>
    <div class="form-group">
    <%= f.label :amount, "Amount:" %><br>
    <div class="col-md-7">
    <%= f.text_field :amount, class: "form-control"  %>
    </div>
  </div>

  <div class ="form-group">
    <%= f.label :date,"Date:" %><br>
    <div class="col-md-2">
    <%= f.text_field :date, :placeholder => 'Select Date and Time', class: "datetimepicker form-control" %>
    </div>
  </div>

 <div class="form-group">
  <%= f.label :category, "Category:" %><br>
    <div class="col-md-4">

    <%= f.collection_select(:category_id, current_user.categories, :id, :name, {}, { :class => "select_box selectpicker picker"}) %>
      <%= link_to "+ Add Category", new_category_path %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description:" %><br>
    <div class="col-md-7">
    <%= f.text_area :description, class: "form-control"  %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :Submit, class: 'btn btn-success', data: { disable_with: "Please wait..." } %>
  </div>
<% end %>


<script>
  jQuery('.datetimepicker').datetimepicker({timepicker: false, format: 'd/M/Y' });
</script>

app/views/expenses/edit.html.erb
<h1>Edit Expense</h1>
<%= render 'form' %>

app/views/expenses/index.html.erb
<h1>Expenses</h1>
<div class="well">
  <%= link_to "+ New Expense", new_expense_path, class: "btn btn-success" %>
  <%= link_to "Download Excel", expenses_path(format: "xls"), class: "btn btn-info" %>
  <div align = "right">
  <%= render 'expense_search' %></br>
  <%= link_to "All expenses", expenses_path, class: "btn btn-primary" %>
  <%= link_to "This date", expenses_path(:type => 'date'), class: "btn btn-warning" %>
  <%= link_to "This week", expenses_path(:type => 'week'), class: "btn btn-primary" %>
  <%= link_to "This month", expenses_path(:type => 'month'), class: "btn btn-warning" %>
  <%= link_to "This year", expenses_path(:type => 'year'), class: "btn btn-primary" %>
  </div>
</div>

<%= paginate @expenses %>
</br>
<%= page_entries_info @expenses %>
  <div align = "right">
  <%= sort_link @search, :amount, "Amount", class: "btn btn-xs btn-primary" %>
  <%= sort_link @search, :description, "Description" %>
  <%= sort_link @search, :date, "Date" %>
  </div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Category</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @expenses.count == 0 %>
      <tr>
        <td colspan="5">
          No expenses found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @expenses.each do |expense| %>
        <tr>
          <td><%= expense.date.to_date %></td>
          <td><%= expense.category.name%></td>
          <td><%= expense.description %></td>
          <td><%= expense.amount %></td>
          <td><%= link_to "Edit", edit_expense_path(expense), class: "btn btn-primary" %>
              <%= link_to "Delete", expense, method: :delete,
                    data: { confirm: "You sure?" }, class: 'btn btn-small btn-danger' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/expenses/index.xls.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Category</th>
      <th>Description</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% if @expenses.count == 0 %>
      <tr>
        <td colspan="5">
          No expenses found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @expenses.each do |expense| %>
        <tr>
          <td><%= expense.date %></td>
          <td><%= expense.category.name%></td>
          <td><%= expense.description %></td>
          <td><%= expense.amount %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/expenses/new.html.erb
<h1>Add New Expense</h1>
<%= render 'form' %>

app/views/expenses/reports.html.erb
<div class= "no-print">
<div class= "pull-right">
<%= link_to "Print", '#', class: "btn btn-primary",
              onclick: 'window.print();return false;' %><br><br>
</div>

<%= form_tag reports_path, method: :get do %>
  <%= text_field_tag 'date_from', '', class: 'datetimepicker', :id => "date_from", placeholder: "From" %>
  <%= text_field_tag 'date_to', '', class: 'datetimepicker', :id => "date_to", placeholder: "To" %>
  <%= submit_tag 'Search', class: 'button search-button' %>
<% end %>
</div>


<div class= "container">
<div class="col-xs-6">
    <h3>Current Week Expenditure</h3>
    <%= line_chart @current_week_expenses.group(:date).sum(:amount) %>
</div>

<div class= "container">
<div class="col-xs-6">
    <h3>Current Month Expenditure</h3>
    <%= line_chart @current_month_expenses.group(:date).sum(:amount) %>
</div>

 <div class="col-xs-6">
    <h3>Current Year Expenditure</h3>
    <%= line_chart @current_year_expenses.group(:date).sum(:amount) %>
 </div>

<% if @range_expenses.present?  %>
  <div class="col-xs-6">
    <h3>Selected Date Range Expenditure</h3>
    <%= line_chart @range_expenses.group(:date).sum(:amount) %>
  </div>

<% end %>
</div>

<script>
  jQuery('.datetimepicker').datetimepicker({timepicker:false});
  jQuery('#date_from').on('change', function(){
  var date = $(this).val().split(' ');
  jQuery('#date_to').datetimepicker({minDate: date[0]});  
  });
</script>  

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
      	<li class="navbar-brand"><%= link_to "Expense Manager", root_path %></li>
        <li><%= link_to "Expenses", expenses_path %></li>
        <li><%= link_to "Categories", categories_path %></li>
	      <li><%= link_to "Reports", reports_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Logout", destroy_user_session_path %> </li>
        <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li> 
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expense Manager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "application", "chartkick" "data-turbolinks-track" => true %>
  <%= javascript_include_tag "//www.google.com/jsapi" %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
  <div class="container">
    <p class="notice"><%= notice %></p>
  	<p class="alert alert"><%= alert %></p>
    <%= yield %>
  </div>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1> Expense Manager </h1>
<p>Manage all your expenses hassle free </p>

<div class="well">
<%= link_to "+ Add Expense", new_expense_path, class: "btn btn-small btn-success" %>
<%= link_to "+ Add Category", new_category_path, class: "btn btn-small btn-success" %>
</div>

<h3>Benefits:</h3>
<ul>
	<li>sorting the expenditures based on the categories.</li>
	<li>sorting the expenditures based on the period of time.</li>
	<li>Addition & deletion of personal categories.</li>
	<li>Graph charts based on certain time periods.</li>
	<li>Download all the expense list in the excel sheet</li>
</ul>